package com.zhubajie.oabern.dal;

import java.util.List;
import com.zhubajie.oabern.bean.City;
import com.zhubajie.oabern.bean.CityExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CityMapper {

    /**
     * 查找指定限制的的数据
     * @param minLimit
     * @param  maxLimit
     * @return 指定的数据
     */
    List<City> findByLimit(@Param("min") int minLimit, @Param("max") int maxLimit);

    /**
     * 统计总数
     * @return 统计结果
     */
    int countNum();

    /**
     * 通过城市名字获取城市信息
     * @param cityName 城市名字
     * @return 相应的城市信息
     */
    List<City> findCityInfoByName(@Param("name") String cityName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int countByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int deleteByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    List<City> selectByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    City selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int updateByExample(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int updateByPrimaryKey(City record);
}