package com.zhubajie.oabern.dal;

import java.util.List;
import com.zhubajie.oabern.bean.Countrylanguage;
import com.zhubajie.oabern.bean.CountrylanguageExample;
import com.zhubajie.oabern.bean.CountrylanguageKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CountrylanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int countByExample(CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int deleteByExample(CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int deleteByPrimaryKey(CountrylanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int insert(Countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int insertSelective(Countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    List<Countrylanguage> selectByExample(CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    Countrylanguage selectByPrimaryKey(CountrylanguageKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int updateByExampleSelective(@Param("record") Countrylanguage record, @Param("example") CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int updateByExample(@Param("record") Countrylanguage record, @Param("example") CountrylanguageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int updateByPrimaryKeySelective(Countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbggenerated Fri Jul 08 09:43:31 CST 2016
     */
    int updateByPrimaryKey(Countrylanguage record);
}